### ISSUE TITLE
will not load addon

### ISSUE THREAD

**Issue by Kilo716** [DanielHazzard/Cure-Please#102]
cure please was running fine, i switched subs was running /sch went to blm. basicly broke cure please. I have deleted it restarted comp, game, cureplease. It just tries to spam abi and nothing happens plesae help/

**Comment by DanielHazzard** [comment]
First things you should do in instance's like this is delete the CurePlease folder (Which I see you did), then download the most recent version, and install it into a brand new folder with a band new name.

So if your previous directory was:

Desktop/CurePlease/CurePlease.exe

try making a small modification like

Desktop/CurePlease2/CurePlease.exe

as I don't know why but somehow Windows screws things up that causes it to sometimes not work even when deleting it all and redownloading it back to the same directory.
