### ISSUE TITLE
not removing debuff in party

### ISSUE THREAD

**Issue by bonz129** [DanielHazzard/Cure-Please#104]
for some reason cure please isnt removing debuffs from party members im pretty sure im checking all the boxes but could someone help me with what boxes to select and anything else i need to do in order for it to remove debuffs. thank you

**Comment by N0isyCricket** [comment]
Hello.

I also have this problem.  Have verified windows firewall settings, addon indicator is green, loads on char and addon displays in chatbox.  Settings in options are all correct and enabled, yet only removes from monitored player.  Works perfectly for duo boxing.  

Thank you for updating this app, love it!

**Comment by DanielHazzard** [comment]
Have you used the BUFFS window to check that the ADDON is reading current buffs active on the party.

**Comment by Haltrius** [comment]
Need to enable the Addon in other options too for -na removal.

**Comment by N0isyCricket** [comment]
DanielHazzard,

Party buffs does show the correct buffs/debuffs.  Monitored player gets everything removed, but 3rd (tri box) or other players get nothing.  Settings are all enabled and port is open.  Does program need to be in any specific location?

**Comment by Haltrius** [comment]
there are two box to check next to players. One to select and the second one to add priority. Did u make sure , you check the first box next to everyone out of your main party?

**Comment by N0isyCricket** [comment]
Yes, as I've said, everything that needs to be checked is checked, other players are getting cured, and auto haste/refresh works (except for flurry).  Its just not removing debuffs from players other than the monitored player.  Also, party 1 has all the checks enabled by default, you only have to do that for party 2 and 3.

**Comment by Haltrius** [comment]
You should not have this issue if the add on is enabled in the settings, and if the addon folder is in windower or ashita addons folder. Is that the casde?

**Comment by N0isyCricket** [comment]
Unfortunately its not that simple.  There are many variables with software that could be the issue.  I feel like I'm repeating myself when I say everything is checked and installed where it needs to be.  I  can post pictures of the settings and screen shots of the app not working if you like.

**Comment by DanielHazzard** [comment]
If the party buffs window does not show other party buffs for any character in the PL's party that are not trust magic then the addon is not receiving the packet data correctly.
