### ISSUE TITLE
cureplease in nasomi

### ISSUE THREAD

**Issue by cajuncooking** [DanielHazzard/Cure-Please#106]
DanielHazzard

Could you/would you please develop and post a guild to make cureplease work on the nasomi server?
I've used it before elsewhere and love it.  So please, help me with this.

**Comment by DanielHazzard** [comment]
CurePlease will work on any version of FFXI that is upto date with FFXI Retail. Older versions will require older versions of EliteAPI to work.

**Comment by cajuncooking** [comment]
I am sure that you are correct, Cureplease would work with any up to date ffxi.  The problem is not with cureplease, that problem is with nasomi server.  No matter what I've tried, all i get is a "file not found" message.  I can't get cureplease to see and link with nasomi.  I do not know the work around for that.  Must be a certain way to install cureplease so it can see and link with the nasomi server.  That seems to be the core issure I am having, not the cureplease program itself.  What I am asking, is for someone much more versed than I am to try and make it work on nasomi and then post the steps taken.

**Comment by EpicTaru** [comment]
There is no way to make it work with Nasomi, like DanielHazzard stated.  The issue isn't with CP itself but with the version of FFXI that Nasomi uses.  Nasomi needs to update to a newer version for CP to ever recognize it.

**Comment by cajuncooking** [comment]
Ok, ty, uninstalling nasomi as of now. Am not happy there. A few of the other private servers looks much more like where I'd rather be.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
