### ISSUE TITLE
Fresh install 

### ISSUE THREAD

**Issue by hedron2003** [DanielHazzard/Cure-Please#109]
i fresh installed the newest release and whenever i try to select PL and monitored player the program just crashes addons in correct spot..no antivirus is stoping it.. uac settings and set to lowest...out of ideas to try..

**Comment by KevinKozan** [comment]
Is it a crash due to `Unable to load DLL 'EliteAPI.dll'`? I'm over at #108 with issues at that exact point as well.

**Comment by DanielHazzard** [comment]
Always confirm you have the required C++ Redists needed. 

VC++ 2010 x86 
http://download.microsoft.com/download/5/B/C/5BC5DBB3-652D-4DCE-B14A-475AB85EEF6E/vcredist_x86.exe

VC++ 2012 x86 
http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU3/vcredist_x86.exe 

VC++ 2013 x86 
http://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe 

VC++ 2015 x86 
https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe

This is 99% the problem when errors occur, please let me know if you have reinstalled them and the problem still occurs.
