### ISSUE TITLE
Auto casting not working

### ISSUE THREAD

**Issue by rivan48312** [DanielHazzard/Cure-Please#117]
Hi Dan

Love cure please thanks a ton.  Having issues getting auto casting to work.  No matter what I try it wont cast on party member or enemy that we fight.  
![Screenshot (1)](https://user-images.githubusercontent.com/56430395/96664796-8fa90780-1321-11eb-8ee2-9a491760006c.png)

**Comment by rivan48312** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/56430395/96664988-e282bf00-1321-11eb-847c-1346d360d9b4.png)

**Comment by DanielHazzard** [comment]
I'll check it out.

**Comment by DanielHazzard** [comment]
Please confirm you have the new EliteAPI.dll file.
