### ISSUE TITLE
Where is the newer addon file located?

### ISSUE THREAD

**Issue by rivan48312** [DanielHazzard/Cure-Please#118]
Where is the newer addon file located?

_Originally posted by @rivan48312 in https://github.com/DanielHazzard/Cure-Please/issues/61#issuecomment-714267707_

**Comment by DanielHazzard** [comment]
included in the .ZIP file.

**Comment by Stunna-Bih** [comment]
I tried all kinds of things after the update i still cant get cure please to select a character

**Comment by DanielHazzard** [comment]
Make sure you have the most recent release as the EliteAPI dll file changed.
