### ISSUE TITLE
Cure Please Not Working

### ISSUE THREAD

**Issue by kylouie1616** [DanielHazzard/Cure-Please#120]
I tried installing the update from today (11-10-20), but cure please is still not working.  The program starts up just fine, but when selecting the characters (PL & Monitoring) nothing loads.

**Comment by Drorond** [comment]
First i tried with the latest release that you can found here https://github.com/DanielHazzard/Cure-Please/releases
But it wasnt working.
Then i tried to replace the EliteAPI.dll from the lastest release with the EliteAPI fix that DanielHazzard posted in the latest closed Issues and now it's working but idk why lol i guess between his post and the release, something changed or it was just me not doing it right^^ (https://github.com/DanielHazzard/Cure-Please/files/5520757/EliteAPI_NotFinal.zip)

**Comment by camosaan** [comment]
@kylouie1616  This issue has been addressed. Please use the latest version of EliteAPI. There has been no change to the CurePlease code base, only the EliteAPI dependency has been udpated by a third-party developer. 

http://ext.elitemmonetwork.com/downloads/eliteapi/

**Comment by kylouie1616** [comment]
Awesome, thank you!  I got it working again.
