### ISSUE TITLE
Cure please not working 

### ISSUE THREAD

**Issue by milkymann** [DanielHazzard/Cure-Please#122]
Cure please won’t work for me after the lat update, I deleted the old version and downloaded the newest version and it still won’t do anything, I run as admin I can select my characters, the addon opens and looks normal it just won’t work I’m at a loss, what am I doing wrong?

**Comment by qimitau** [comment]
You need to update a single file called EliteAPI.dll in CurePlease Folder.
http://ext.elitemmonetwork.com/downloads/eliteapi/

**Comment by milkymann** [comment]
Ok I downloaded that eliteAPI file and thought I replaced it in cure please I must not have done something right, thank you, I will try again!

**Comment by Smobo732** [comment]
Same here, old cureplease deleted. new version downloaded today sees characters, lets me select them, then nothing. i usually see windower show some text with the IP but thats not happening. loading a save also does nothing.

**Comment by milkymann** [comment]
Fixed!!! Thank you

**Comment by milkymann** [comment]
> Same here, old cureplease deleted. new version downloaded today sees characters, lets me select them, then nothing. i usually see windower show some text with the IP but thats not happening. loading a save also does nothing.



> Same here, old cureplease deleted. new version downloaded today sees characters, lets me select them, then nothing. i usually see windower show some text with the IP but thats not happening. loading a save also does nothing.

Do what qimitau told me to do it worked

**Comment by lewyo** [comment]
I can add to this that i've been using this for awhile now and since the November update and the latest release this does not work, It shows all in pt as inactive and it makes no attempt to load the addon.

**Comment by lewyo** [comment]
ok read up and got it working, Please add all the updated files in the future i just lost 3h tryng to make this work due to a bad download

**Comment by DanielHazzard** [comment]
Fixed, should be the correct file now, Sorry about that.
