### ISSUE TITLE
cure please error message

### ISSUE THREAD

**Issue by Latravant** [DanielHazzard/Cure-Please#123]
i'm getting a windows pop up error 
unhandled exception has occurred in your application, if you click .....

Could not load file or assembly 'EliteMMO.API, version 1.3.00.
Culture = neutral. PublicKeyToken=null' or one of its dependencies. the
system cannot find the files specified

i downloaded the new eliteapi file and installed it. 
i copied the elitemmo.api file from here and installed it, erasing the old files first as i seen suggested in previous issues.

**Comment by Latravant** [comment]
a log in the error message has this:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'EliteMMO.API, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'EliteMMO.API, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'
   at CurePlease.Form1.checkSCHCharges_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by DanielHazzard** [comment]
Seems like something could be deleting the required .DLLs
