### ISSUE TITLE
Update link in About menu to point to correct repository for latest version

### ISSUE THREAD

**Issue by EpicTaru** [DanielHazzard/Cure-Please#130]
The link to the latest version of Cure Please, in the About menu, still points to Atomos' github (https://github.com/atom0s/Cure-Please), on which the latest version indicated is 2.0.0.8.  Can this please be updated to point to your github repository with the actual latest version, DanielHazzard?

![image](https://user-images.githubusercontent.com/26195580/103490990-5131cd80-4de5-11eb-81aa-8f89c3dc0fa5.png)

![image](https://user-images.githubusercontent.com/26195580/103491016-96ee9600-4de5-11eb-80d1-9a210d0d8552.png)

**Comment by DanielHazzard** [comment]
Will do.

Edit: Will be fixed in the next version, Thank you and closed.
