### ISSUE TITLE
FFXI not found

### ISSUE THREAD

**Issue by justinmd1911** [DanielHazzard/Cure-Please#14]
after placing this in the add on folder in ashita, the program will run, but with message that FFXI not found. Running windows 10. Wondering if there was anything else I need to do. Thanks I’m a advance.

**Comment by mbout4it** [comment]
Also have this issue.

**Comment by nfaletra** [comment]
I had this issue when connecting to Private Servers. Renaming xiloader.exe to pol.exe (renamed pol.exe to polorig.exe) fixed it. Would be nice if you could set what instance name to look for.

**Comment by DanielHazzard** [comment]
Sorry, just noticed this. I'll include a search for xiloader.exe as well, if there are other common file names let me know and I'll include them too.

**Comment by tipwell** [comment]
Could you add edenxi.exe as well? They implemented a new boot-loader that you cannot rename. Thanks
