### ISSUE TITLE
Addon commands

### ISSUE THREAD

**Issue by Comgamer7** [DanielHazzard/Cure-Please#144]
I know the addon has some hidden commands that you can type out or send to start/stop it, but i cannot remember them. Do you know the commands by chance?

**Comment by twothreeforme** [comment]
I currently use the start/stop command: 
//cpaddon cmd (stop/pause | start/unpause | toggle)
This only works when the addon button is green in CP. Hope this helps.

**Comment by Comgamer7** [comment]
That is what i was looking for, TY so much!

**Comment by johnarnfield** [comment]
I'm having trouble with this since the update, and having to install new DLLs. Anyone else? Addon button stays red, though cpaddon is being loaded in game. The start/stop commands aren't doing anything, neither are the keybinds.
