### ISSUE TITLE
Unable to load DLL 'EliteAPI.dll' error:  The specified module could not be found. (Exception from HRESULT: 0x8007007E).

### ISSUE THREAD

**Issue by EmperorGestahl** [DanielHazzard/Cure-Please#146]
I continually get this error every time i try and select the selected PL.  Everything had worked fine previously; the file is there in the correct pathway but it does not work now.  I did have a BIOS update yesterday and am assuming it is to blame somehow.  Any ideas or help would be much appreciated.

**Comment by DrakeFS** [comment]
Make sure you have installed the prerequisites for the EliteAPI.dll, you will need the x86 versions where applicable.

- Microsoft .NET Framework 4.5
- Visual C++ Redistributable Packages for Visual Studio 2013
- Visual C++ Redistributable Packages for Visual Studio 2015
