### ISSUE TITLE
Not working after February 10 Patch

### ISSUE THREAD

**Issue by Zatcaskagoon** [DanielHazzard/Cure-Please#147]
The program no longer works after the recent patch. Mule no longer takes actions. No buffs no cures. APIs are the latest version. The program is connecting to the addon lua properly.

**Comment by kylouie1616** [comment]
Mine also doesn't work.  The weirdest part is that it DOES work when I FIRST load up Curepls in town, but once I zone anywhere it DOESN'T work anymore

**Comment by Mercurian** [comment]
It needs a new API. I'm really curious why it hasn't been pushed yet, normally it's out within a couple hours at most.

**Comment by Zatcaskagoon** [comment]
> It needs a new API. I'm really curious why it hasn't been pushed yet, normally it's out within a couple hours at most.

Have you tried the addon? Can you confirm it is not working? It honestly doesn't seem like an API issue.

**Comment by Flyingtaru** [comment]
Confirmed not working since update. It loads, can be setup, but doesn't act on character to start buffing/curing.

> > It needs a new API. I'm really curious why it hasn't been pushed yet, normally it's out within a couple hours at most.
> 
> Have you tried the addon? Can you confirm it is not working? It honestly doesn't seem like an API issue.

**Comment by Flyingtaru** [comment]
If not API, then CP must have some inventory references (weapons?) that need to be added (BRD)?

**Comment by Mercurian** [comment]
It's always the API

And it's times like these we realize we rely entirely too heavily on one person

**Comment by Flyingtaru** [comment]
I'm assuming it's a bit of both.

**Comment by Zatcaskagoon** [comment]
> 

The reason I say that the API seems fine is that the application is detecting the actions of the player. If a spell is used by the player the application detects the action. Nothing is happening automatically though. So that would indicate the applications are communicating.

**Comment by kylouie1616** [comment]
Again, Mine WORKS when I first appear in the game IN TOWN.  As soon as I zone it stop working ANYWHERE (meaning even if I return to town it doesn't work)

It's odd that it works when I first appear in game then it stops after zoning.

**Comment by Wyrmnax** [comment]
> It's always the API
> 
> And it's times like these we realize we rely entirely too heavily on one person

Windower, Gearswap....

These are all works of 3-4 ppl at most that are completely detached from SE. And if one of them decides "eh, don't want to anymore" the game probably dies.

Imagine if the team that maintains gearswap decides they dont want to play anymore...

But yeah, not working anymore

**Comment by DanielHazzard** [comment]
Requires the new API - http://ext.elitemmonetwork.com/downloads/eliteapi/
