### ISSUE TITLE
New EliteAPI v1.4.1.0

### ISSUE THREAD

**Issue by RoXXioN** [DanielHazzard/Cure-Please#148]
i Just have one think so say,
Thank You!
Thank you for ubdate the EliteAPI, and bring the CurePlease back to run.
Thank You so mutch!

**Comment by Stavorm** [comment]
where do u go to get the new api?

**Comment by RoXXioN** [comment]
http://ext.elitemmonetwork.com/downloads/eliteapi/

**Comment by Stavorm** [comment]
Thank you!
