### ISSUE TITLE
Additional addon, missing?

### ISSUE THREAD

**Issue by ifattah** [DanielHazzard/Cure-Please#15]
With the correct EliteAPI/MMO DLLs, this works well.

However, when I shutdown the program, it tries to unload an ashita addon called "cureplease_addon".

Is this intentional and if so, where can I find it, source if possible? 

Thank you!

**Comment by ifattah** [comment]
This can be fixed. The addon is a Lua file included in the release 2.0.27 ZIP file but not in the source of the project.

**Comment by DanielHazzard** [comment]
The fix has been added, so closed.
