### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by wbnightwolf** [DanielHazzard/Cure-Please#17]
Microsoft .NET Framework error.  Continue or quit.  Only happens on the newest (.28) .  Have not isolated the trigger to make it happen
![capture](https://user-images.githubusercontent.com/34048380/34909951-a886708c-f879-11e7-9ed8-f632f02d59e9.JPG)

**Comment by DanielHazzard** [comment]
Should be fixed, closed.
