### ISSUE TITLE
Vision Issues

### ISSUE THREAD

**Issue by Anuyffxi** [DanielHazzard/Cure-Please#20]
I'm so sorry but this is a must fix. I'm forced to run my settings at 720p because i'm almost blind so im not able to change settings or load or save the settings because the button is below the screen and I can not put the page full screen because the box to make it fit to screen i not available which means i'm not able to fix the page.

**Comment by DanielHazzard** [comment]
I'll re-enable the fullscreen butter in the next update. Sorry about this.

**Comment by Anuyffxi** [comment]
thank you so much ^^


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Anuyffxi** [comment]
Is there a reason why i cant find the haste function on the program but
theres a place to do recast timer on haste?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
