### ISSUE TITLE
Ninja spells:  Utsusemi: Ni, Utsusemi: Ich added

### ISSUE THREAD

**Issue by salazer** [DanielHazzard/Cure-Please#21]
I was wondering if ninja spell's could be added for dual wield healing clubs like Nibiru Cudgel x2

**Comment by DanielHazzard** [comment]
I'm sorry, I don't understand. Spells like what? Utsusemi is already available.

**Comment by salazer** [comment]
I was using a older ver., I saw the Utsusemi box when i updated sorry about that.

**Comment by DanielHazzard** [comment]
No problem. It happens.
