### ISSUE TITLE
Help with using 

### ISSUE THREAD

**Issue by darkchylde01** [DanielHazzard/Cure-Please#25]
Trying to use cure please on whm but having trouble understanding how it works for example I have the cure 3 box checked off and next to it where it says (use when [400] hp is lost) it never uses the spell then instead of using cure 3 it’ll use cure v which also checked to use when 700 hp is lost. The same problem occurs with curaga. PLEASE HELP. thanks in advance

**Comment by DanielHazzard** [comment]
No reply, assumed solved.
