### ISSUE TITLE
2 Issues noted as of 4/16/2018

### ISSUE THREAD

**Issue by eckamus** [DanielHazzard/Cure-Please#27]
Spacing error in GEO Indi spells, there is a space before the spell name and does not properly cast. Spells affected are Indi-Malaise and Indi-Fade. Present in both Indi and Entrust spells sections.

CurePlease_addon throwing an error with latest update 2.0.3.3

Error: CurePlease_addon: Lua runtime error: CurePlease_addon.lua:144: attempt to perform arithmetic on a nil value

**Comment by DanielHazzard** [comment]
Thanks I'll get those fixed for RC3.

**Comment by DanielHazzard** [comment]
Fixed.
