### ISSUE TITLE
Character locks on to Enemy

### ISSUE THREAD

**Issue by jubae** [DanielHazzard/Cure-Please#28]
Hi, I have been using this for a while and it's amazing. More recently I have been having the issue where the PL character keeps locking onto the mob and therefore won't follow the character I choose. As soon as I click to release target lock, the PL runs off to follow correctly, but then on the next mob the exact same thing happens again. 

my PL character is not engaging any mobs, just locking on to them every pull :(

Many thanks for any help with this.

**Comment by DanielHazzard** [comment]
The bot uses /assist to target the mob when you enable the hate spell or GEO spells, but should cancel it straight after.

Do you enable either function?

**Comment by jubae** [comment]
I have the geo spells enabled, The pl toon is a geo. But it doesn't disable the target lock,just  stands at the mob the whole fight. I haven't enabled any /assist though.  I just need OT to release lock so it can follow my other toon :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DanielHazzard** [comment]
I will look into it tomorrow.

You don't enable/disable /assist as it's necessary for casting the GEO spells such as Frailty, as <bt> doesn't always work whereas /assist does.

Like I said, what should happen is /assist, cast GEO spell, remove target but something seems to be interferring with the removal for you, I'll see if I can figure it out.

**Comment by DanielHazzard** [comment]
EDIT: I plan to push a release tomorrow to fix this.

**Comment by DanielHazzard** [comment]
I pushed a release, please let me know if this has fixed it.

**Comment by jubae** [comment]
Hi buddy,


Not sure what you have done, but that seems to have sorted out the issue! Thank you very much for your dedication and hard work! 😊


Mo


________________________________

**Comment by DanielHazzard** [comment]
Glad to hear it.

Just set it to wait half a second after casting and then cancelled the target.
