### ISSUE TITLE
Is Enable/Disable Debuff removal working? Auto-Buffs?

### ISSUE THREAD

**Issue by ifattah** [DanielHazzard/Cure-Please#30]
Do I have to right-click every character and select "Enable debuff-removal" in order for stats like Paralyze/Silence/Doom/etc to be removed?

(1) I assume 'Enable PL debuff' removal will remove debuffs on the support character
(2) I assume 'Enable Monitored player debuff removal' will remove debuffs on the monitored character 
(3) I assume under Debuff Removal, if I uncheck "Remove from selected players only' will remove debuffs from all 18 checked players if in a full alliance

Regarding buffs: I also notice that selecting Auto-Haste for the monitored player doesn't take effect until I actually select 'Haste' on monitored player ....but doesn't always re-cast haste. It will continue to recast haste every 3 minutes  or whenever it wears on the monitored player ....or it simply never does it at all. I'm not sure how to reproduce. Could this be happening because I sometimes select a new PL character from the drop-down without closing / restarting the application?

**Comment by DanielHazzard** [comment]
No that is only enabled if you enable "Remove from selected players only" otherwise it defaults to the six characters in your party.

1. Thast's the PL themselves.

2. Thats the MONITORED player selected in the second combo box.

3. No that means to only remove them from characters you've added to a list under the Enable debuff-removal you mentioned in the previous comment.

It shouldn't, though it will mess it up if the player party position is changed, for example: It's the second character on the first PL, then the third character on the second PL.

Haste without the add-on works on a timer basis, so if you get interrupted via movement, or another spell casting it will register the time and have to wait until the next 3 minutes to recast. It's best to use the Add-on as it will recast if the buff is missing.

**Comment by ifattah** [comment]
OK, wow, thank you. What you said perfectly describes the problems I was having.

1.) Going forward, I'll exit / restart Cure Please if my monitored character's position changes with respect to the PL. 
2&3.)  I will uncheck "Remove from selected players only" so that I can properly debuff characters in my PL's party.

Also, FYI: I notice that if you do have "Remove from Selecteded players only" and then pick "Enable Debuff Removal" by right-clicking on a character. How do you disable debuff removal for that character only?  (I mean, the option when right-clicking still says "Enable Debuff-removal"...

Just a thought, I prefer to know that debuff removal is happening on all 6 of my PL's party. (And if I check everyone in the alliance, all 18 are getting healed, and 12/18 are not having debuffs removed, because they are outside of the main PL party.

**Comment by ifattah** [comment]
Last question. Using 2.0.3.3, why is "Reduce Recast Timer by 50%" grayed out? I can't check/enable it all. :( ![image](https://user-images.githubusercontent.com/4296875/39670742-67fc62a2-50d9-11e8-8e40-c9f26c4267d3.png)

**Comment by DanielHazzard** [comment]
I'll add it in a future update.

Because that function has been removed, I plan to remove it at a later date but need to add a check to block it breaking peoples settings files.

**Comment by ifattah** [comment]
I was super disappointed to see that function removed. It worked fine for me in versions including and before 2.0.2.7.

Thanks Daniel.

**Comment by DanielHazzard** [comment]
Do the debuffs show in the Party Buffs window?

**Comment by Blitzjr** [comment]
One second. I wanna say yes. I select the erase window.

**Comment by Blitzjr** [comment]
It works for PL, but doesn’t work for others even if I select it on the menu through Enable Debuff. It’s just not reading party members statuses I think

**Comment by DanielHazzard** [comment]
![party_buffs](https://user-images.githubusercontent.com/20212218/40589871-3c86944c-61ed-11e8-9795-b6b22e3c74b8.jpg)

I mean in the Party Buffs window, a screenshot below.

**Comment by DanielHazzard** [comment]
That means an error has occurred from sending the data, this could be one of many things.

1. You have not checked "Enable CurePlease Add On" in the OTHER OPTIONS tab.

2. You have not checked "Enable party-na removal" on the DEBUFF REMOVAL tab.

3. The Add-On did not load in the game, the should happen automatically as the bot runs or when unpaused. You can also add this using the command _//lua load CurePlease_Addon_ (Windower) or _//addon load CurePlease_Addon_ (Ashita) not if you use any settings other than the default IP/Port you need to set the settings as well using the following command: _//cpaddon settings IPADDRESS PORT_ (Windower) _/cpaddon settings IPADDRESS PORT_ (Ashita)

4. The IP Address / Port number do not match. You can confim this by using the WINDOWER/ASHITA command: _//cpaddon check_ (Windower) or _/cpaddon check_ (Ashita) and comparing it to the settings in the PROGRAM OPTIONS tab.

5. You did not allow the CurePlease Program access in your Firewall Settings.

**Comment by Blitzjr** [comment]
Shoot ok thanks I’ll check those out ASAP and let you know
