### ISSUE TITLE
Monitored player issue

### ISSUE THREAD

**Issue by zylakitty** [DanielHazzard/Cure-Please#31]
Hello, I'm trying to use this and I can't quite figure out what I'm doing wrong. I want to set up the bot to cast spells on targets engaged by my party members, however I can't set any of those party members as the monitored target it only gives my character as an option for a monitored target, thus it is not casting anything on engaged enemies. Can you just not make other party members the monitored target? Does it have to be a 2nd character controlled on your system?

**Comment by DanielHazzard** [comment]
Monitored player can only be set to a player on your PC, if you only have one account than PL and Monitored should be that person.

**Comment by zylakitty** [comment]
ok so can't really do what I need then. thnx
