### ISSUE TITLE
Geo targeting issue

### ISSUE THREAD

**Issue by MilitantRav** [DanielHazzard/Cure-Please#36]
When the bot targets the engaged mob it wont cast the geo spell. It then disengages and this cycle repeats.  I have tried the settings of automatic spell casting with enemy based Dia II as the spell target doesnt seem to matter. Just trying to get it to auto cast on the engaged mob.

**Comment by DanielHazzard** [comment]
Does it have an error on the bot or in the game when it tries to cast? Or does it simply not cast.

**Comment by MilitantRav** [comment]
It targets the mob locks on unlock this just cycles, I might not be setting the bot up right but when I talked to another user of cure please hers seems to work but I cant for the life of me figure out what I'm doing wrong.

**Comment by DanielHazzard** [comment]
And it's just those spells not working, everything else works?

**Comment by MilitantRav** [comment]
Yea just Geo spells indi works and the self buff and cures all work

**Comment by MilitantRav** [comment]
I did notice last night that when it tries to cast the geo spell I get a packet lost I didnt notice it until I was testing it with all the different settings and its just on the geo spell no others

**Comment by DanielHazzard** [comment]
Okay, I'll look into it thanks for the report and updates.

**Comment by kittaru** [comment]
A further note on this, I have found this error to only happen on force spawned enemies like those in Escha/Reisenjima. It doesn't happen when killing Apex mobs for me.

**Comment by MilitantRav** [comment]
I was running the latest release last night in Omen on my geo alt and its was doing the same thing target unlock packet lost recover packet never cast the geo bubble. I'm going to disable the AV on my gaming pc and test it again maybe this weekend but it seems its the packet lost that is keeping it from casting.

**Comment by MilitantRav** [comment]
still getting packet lost on geo spell casting and the strange target lock unlock, removed AV on the machine to make sure it was not the issue but didnt change

**Comment by anjiax** [comment]
Encountering the same issue, 

Also cannot get bard songs to work - my bard will cast 1 song, wait about 30 seconds, then sing that same song again. Happy to give any details on settings. 

Indi spells, cures seem to work fine, no issues.
