### ISSUE TITLE
Bring back 50% faster casting?

### ISSUE THREAD

**Issue by ifattah** [DanielHazzard/Cure-Please#37]
Can you bring back faster casting with the grayed out checkbox? (Even if it messes with people's settings, I still find settings to not be saved occasionally, but not sure if that is related).

Still, I for one, would be willing to eat that loss to keep that 50% casting speedup that was grayed-out a few releases ago.

**Comment by DanielHazzard** [comment]
Both the ones now in CurePlease (original and packet) should be faster than 50% fast cast ever was.

Is that not the case for you?

**Comment by ifattah** [comment]
Unfortunately, no. The time between cures (no debuffs / buffs or anything to case in between take about 2-2.5x longer than when that 50% box was available. Should I share my settings file? I use CurePlease exclusively as WHM99/SCH49.

**Comment by DanielHazzard** [comment]
If you don't mind, it may help me to rule out the problem.

**Comment by DanielHazzard** [comment]
Thank you, I'll look into it.

As an aside, I made adjustments for Packet fast cast for my next update, don't know if you want to try that version.

[CurePlease_2.0.3.4.zip](https://github.com/DanielHazzard/Cure-Please/files/2193971/CurePlease_2.0.3.4.zip)
n.

**Comment by ifattah** [comment]
I will definitely try your provided version 2.0.3.4 right now. Thank you!
