### ISSUE TITLE
Debuff Removal not working on party members

### ISSUE THREAD

**Issue by L57703** [DanielHazzard/Cure-Please#38]
Can't seem to get this working. I started from a fresh download of v2.0.3.3 RC4. I have Enable party - na removal checked (has all but erase checked in party debuffs) and the enable cure please addon checked in other options and it loads the addon fine in ffxi(windower), but it won't remove any debuffs from pt members.

If i enable PL debuff remove or monitored player debuff remove it works for that one character but can't get it working for party members.

It used to work for me in older versions but after this ffxi update it no longer works for me.

**Comment by DanielHazzard** [comment]
Can you confirm they are being read by the addon by using the PARTY BUFFS window. 

Simply open it, then buff a PT member.

**Comment by L57703** [comment]
I did more testing. It works but only if the 1st character is the only character running and you start cure please. The second you load up another character with another cure please the 1st cure please stops reading party buffs (and of course the 2nd cure please doesn't read buffs either). Even if you close the 2nd or 3rd character and 2nd or 3rd cure please the party buffs stay blank till you close out all your ffxi and cure please.

The issue seems to be running multiple cure please are causing the party buffs to stop working.

I'm using windows 10 build 1803 (windows firewall off, all programs ran as admin) and your newest release Cure Please v2.0.3.4 and up to date windower.

**Comment by ifattah** [comment]
For each running fire please instance, change the port number of the CurePlease_addon in Settings, before pressing start?

Or maybe randomize the port number for a range between 19000-20000?

**Comment by L57703** [comment]
I changed port to 19800 first like you said. Selected the 2nd character as main/monitored. Checked with the cpaddon check to make sure correct ip/port are being used and they are. Hit start on cure please and then bring up the party buffs window and cast protect on 2nd character and nothing shows. Also some time after loading the 2nd cure please the 1st one stopped showing buffs.

**Comment by ifattah** [comment]
In the past, when I see no buffs in the party buffs window, I do a "/addon list" to check if the addon is in an error state. If it is, I /addon unload/load it. If I still see an empty screen, I check my windows and Norton firewalls, which after a Windows Update or Norton File definitions update can arbitrarily block the local port used by the CurePlease addon.

**Comment by L57703** [comment]
I've unloaded all addon/plugins in windower, done the lua unload/reload on cureplase_addon. it says its loaded but nothing in party buffs show up after the 2nd cureplease is loaded. I even did a fresh install of windower to make sure there wasn't a problem there.

I've even tested having a unique folder for each cure please instead of loading them all from 1 folder. Even put them in C:\ and C:\Program Files (x86) and even an external drive thinking something like that might help

A few of my friends also have this problem, they are on the lastest windows 10 also.

My windows 10 is bare bones as it will let me go, turned off windows firewall, turned off bit defender (no virus protection at all), security stuff set to low/off. And ya i know i have to redo these settings every time it updates which sucks. I have all the Microsoft Visual C++ Redistributable and all the .net frameworks even uninstalled/reinstalled/repaired to make sure wasn't missing stuff or something went bad. The EliteMMO System Checker shows all green. I even went as far as doing a fresh windows install and same problem still exists.

**Comment by DanielHazzard** [comment]
You can always do the command _/cpaddon check_ which will show the PORT and IP ADDRESS registered with the addon. The addon will only work if CURE PLEASE and the ADDON have the same IP / PORT.

Always remember, when more than ONE CurePlease instance is loaded with the ADDON active, they must EACH have a different port number, which needs to be set up (Usually automatic if before BOTH PL and MONITORED are SELECTED) via the command _/cpaddon settings IP POR_T for example (/cpaddon settings 127.0.0,1 19234)

**Comment by L57703** [comment]
Load cureplease (#1) go to options its has 127.0.0.1 19769, select pl/monitored player (whm1). In game do /cpaddon check and it shows 127.0.0.1 19769. Open party buffs and cast single protect and it works

Load cureplease (#2) go to options set port to 19800 from 19769, select pl/monitored player (whm2). In game do /cp addon check it shows 127.0.0.1 19800. It has the correct ip/port. Open party buffs and single target shell, nothing. And now 1st cureplease no longer shows buffs.

I try again from scratch closing all ffxi and cureplease and reloading the 1st then the 2nd cureplese but this time on i do a /cpaddon check and its perfect again 127.0.0.1 19800 and then do a /cpaddon settings 127.0.0.1 19800 to make sure the ip/port is correct followed by another check to insure its right and it is. Cast a single target shell and nothing in party buffs. And the 1st one loses party buffs again.

I've tried different ports from 5000-65535, loading whm2 1st, having both programs up and running with correct ports before selecting character. Whm1 and whm2 in there own pt, together, solo and nothing works. Once i select the 2nd character all party buff reading ends.

**Comment by DanielHazzard** [comment]
Each CURE PLEASE instance must have a differed PORT.

**Comment by DanielHazzard** [comment]
Understood, apologies I misread. I shall try to see if I can replicate it in the next hour or so, sorry for the inconvenience.

**Comment by DanielHazzard** [comment]
So I can replicate the SECOND account not showing the buffs, that said, I can not replicate the breaking the first account.

Hopefully, by fixing the two accounts problem, it may have the side effect of the first account being blocked.

**Comment by DanielHazzard** [comment]
Okay, I've attached a new CURE PLEASE version, can you test this one.
[CurePlease_NetworkFIX.zip](https://github.com/DanielHazzard/Cure-Please/files/2237193/CurePlease_NetworkFIX.zip)

**Comment by L57703** [comment]
Doesn't work, downloaded Cure Please v2.0.3.4 to its own folder on C:\cpfix then downloaded the CurePlease_NetworkFIX.zip and replaced the .exe then loaded whm and 1 instance of cureplease only and nothing in party buffs.

Then I went back to 2.0.3.3 (which worked before) with just whm and 1 instance of cure please loaded and now its not even working for party buffs, even restarted the pc just in case and nope. Now its not even showing party buffs now =/

**Comment by L57703** [comment]
Did a few more tests of closing ffxi / cureplease and reloading just 1 ffxi and 1 cure please instance trying out different characters and its cureplease folder (i have a folder for whm1, whm2, geo, brd) It stopped showing up in netstat /a /n /o | find "19769"

Even thought cureplease was running and said it connected on port 19769 in the program and ffxi check said ip/port were correct, windows 10 didn't show the port being used with netstat /a /n /o | find "19769". Even tried different ports nothing, took a restart of pc for netstat to show ports being used again but just after 1 or 2 closing of the programs the ports stopped showing up in netstat.

**Comment by Bigiron60T** [comment]
I'm having the same issues with party buffs.  I've changed the ports for each instance. First instance will read party buffs, but additional instances of cureplease will not.  After closing out the first instance and reopening it no longer reads party buffs.  I too am respectfully requesting assistance.  Just wanted to add an additional voice to this discrepancy.  I'm enjoying the troubleshooting and look forward to a fix.

**Comment by DanielHazzard** [comment]
Just a quick query, I'm sure it's not the case, but are either of you LOADING SETTINGS automatically, as that would change the port again. 

If possible could you try placing CurePlease in a different directory and try again to see if it's a bug some people suffer from with old data sticking for some reason.

**Comment by Bigiron60T** [comment]
Auto load settings are not active.  More info i noted today.  Using multiple instances of cureplease with different ports and applying or removing a buff to a party member,  not the selected player, will start the party buff monitoring.  Reapplying a buff that is already active will not start party buff monitoring.  Tested using cureplease with the same and different directories.  Also tested with Windower public and Dev versions.  With and without having extra addons/plugins loaded.

**Comment by L57703** [comment]
No auto load settings, straight out of the box settings just changing port in settings and using the networkfix version u posted.

I tried what Bigiron60T said and still no go for me. The 2nd instance of cureplease still won't show party buffs. Cureplease instance 1 whm1 and mule1 show buffs like he said, but cureplease instance 2 with whm2 and mule2 in there own party still won't show party buffs.

Also i keep getting this error if i leave the pt buff window open for more than a few mins

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at CurePlease.PartyBuffs.update_effects_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2101.1 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Cure Please
    Assembly Version: 2.0.3.3
    Win32 Version: 2.0.3.3
    CodeBase: file:///C:/cpnetworkfix/Cure%20Please.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
EliteMMO.API
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/cpnetworkfix/EliteMMO.API.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by L57703** [comment]
Also with the networkfix version in Other Options if you have automatically cast spell to place yourself on the hate list checked, spell type party based and spell name dia/dia ii (might be just any spell) it just locks the program into trying to cast that spell non stop and won't do anything else.

This works just fine in 2.0.3.3 and 2.0.3.4

**Comment by DanielHazzard** [comment]
@Bigiron60T

Reapplying buffs already won't update the bot, unless one is lost or a new one gained by a PT member. This is because the Packet doesn't send the command unless it's changed from the last time it was sent. The command packet doesn't get sent when the PL is the only one benefitting the buff, it will only be sent when one of the 5 members of the PL's party benefits a buff. This is done by FFXI and I have no way to change this. All the CurePlease Addon does is read that packet and sends it to the bot.

On the off chance it helps to verify how the bot works, then I shall as it may be your problem.

The addon waits to receive a specific packet using ID 0x067 this packet contains amongst other data all the Buffs/Debuffs of the player characters party, this packet is sent when a new buff/debuff is received by the 5 members of your party, or a current one wears off, this packet will not be activated/sent when a buff/debuff effects the PL.

Once the packet is received it then sends that data in a formatted string via Network Socket to CurePlease, CurePlease then reads this packet, separates it into a format I can then create a list of, for example, the packet Received is: buffs-name-idsSeperatedByCommas (example: buffs-JohnDoe-12,13,14,126) CurePlease the separates this into the list I need so

buff- is removed as it's only use is to easily tell me what command was sent and where to go with it, all content after that and up to the next - is taken as the Character Name for the list. and the remainder after the next - are stored as Buffs for that character, this list is then called to see whether a buff or debuff removal spell is needed.

So the list in example would be:

CharacterName = "JohnDoe",
CharacterBuffs = "12,13,14,126"

-

@L57703

You certainly seem to be having a problem with the second bot somewhere, I'm not quite sure as judging by the following post it's as if the first PL is receiving the packet for Cure Please #1 and #2 for them to both show up there, which shouldn't be happening. 

Thank you for the error reports, I'll check them out. Apologies for that.
