### ISSUE TITLE
Please Support JPver Client 

### ISSUE THREAD

**Issue by oppipp** [DanielHazzard/Cure-Please#39]
JP client, the format of the macro is different, so it can not be used

example

English　/ma Cure
JP /ma ケアル
English　/ma Cure VI
JP /ma ケアルVI

Can you switch between JP and EN with AutoFill like Easy Farm or can you use it for Japanese skill name and addition?

**Comment by DanielHazzard** [comment]
I'll look into it, but I make no guarantees.
