### ISSUE TITLE
Party Buffs window not populating.

### ISSUE THREAD

**Issue by grahf4441** [DanielHazzard/Cure-Please#40]
Only 1 instance of game running
V2.0.3.3
Ran as admin, UAC set to lowest setting, Windower4 addon enabled. Other Options CurePleaseAddon selected.

I'm looking for automatic debuff removal for the party, and i've read a lot of issues and it seems to stem from the buff window not functioning correctly. Not really sure where else to look here, i don't see any window event errors, addon from download is loaded and everything is run with full privs. Bot seems to function correctly with the exception of this huge piece.

thanks

**Comment by grahf4441** [comment]
Just realized I'm using V2.0.3.4 release download (in about it says V2.0.3.3)

unsure if this is a problem or related, when i do type pcaddon i get an error in the windower console, with line 19 of the lua addon.

    local cmd = string.lower(input)

maintenance is going on right now so i cant get the exact wording.

**Comment by grahf4441** [comment]
![image](https://user-images.githubusercontent.com/42259699/43942725-b502570e-9c3e-11e8-8a0c-ea88df189d1a.png)

also testing older releases ive noticed when opening an old client then attempting to open a new client even after removing the older one, it defaults to the older client.

**Comment by DanielHazzard** [comment]
You will get an error if all you type is cpaddon you've not added a command.

The accepted commands are: 

cpaddon check 
cpaddon settings IPADDRESS PORTNUMBER

You want to do **cpaddon check** to confirm the IP and PORT are the same as CurePlease.

Also the DEBUFF window will not show unless you cast a buff/debuff or one is removed by a party member other than the PL and not a trust, as the PACKET is only sent in those occasions.
