### ISSUE TITLE
Brd song delay and JA usage

### ISSUE THREAD

**Issue by gminyanou** [DanielHazzard/Cure-Please#41]
Would it be possible to reduce the time between songs cast? Currently it waits until the casting bar is completely done before moving on to the next song.

Nightingale and Troubadour are the only JA's used, and currently they are used at random times. Macarto is not used at all. When you hit start, it will play songs first, then used JA's some random time later.

Minor inconveniences but would be interested to hear if there are any solutions.

**Comment by DanielHazzard** [comment]
It's supposed to use the JA's before songs if they are available. As for cast delay, this is only possible via the PACKET function.
