### ISSUE TITLE
In 2.0.3.6 require strings is actually stringex in Ashita.

### ISSUE THREAD

**Issue by ifattah** [DanielHazzard/Cure-Please#43]
Just something I needed to change after downloading the latest release.

Also, cureplease addon is only showing me buffs from the monitored player and not everyone in my party (currently a 2-person party). Is this intentional?

Thanks!

**Comment by DanielHazzard** [comment]
The packet that is read contains all the members of the PL's party bar the PL.

**Comment by ifattah** [comment]
Thanks!
