### ISSUE TITLE
Omen floor change while casting interrupts workflow

### ISSUE THREAD

**Issue by zombie343** [DanielHazzard/Cure-Please#44]
I was casting a spell (aurura storm) while in omen. LS member takes up to the next floor and Cure please stays on "Casting Aurora storm" and doesn't proceed to follow any further actions. No curing, buffing, item-uses, etc. 

I didn't enable/re-enable the bot. I simply manually casted aurora storm and the boy continued happily along as expected. I assume the terminating condition for a spell being cast, was interrupted by zoning to the next floor in omen?

I'm using 2.0.3.6 btw.

**Comment by DanielHazzard** [comment]
Yeah, this will be due to the bot getting stuck, I added a check to reduce this, but it must not have kicked in, I'll have to check this out.
