### ISSUE TITLE
Alliance

### ISSUE THREAD

**Issue by bjggi** [DanielHazzard/Cure-Please#49]
Hello

Sorry, probably more like a Question than a Issue. As a WHM, is there an option when a Party Member or the monitored Player drops Protect/Shell/Boost/Barstatuses etc., it reapplies them?

For example, when the WHM still has Pro/Shell, and the Monitored Player doesn't, it won't cast Pro/Shell on him.

Is there an option i'm missing? 

Thank you!

**Comment by DanielHazzard** [comment]
Yes, Protect/Shell etc should be under either the MENU or AUTO option next to the character name, can't remember which.
