### ISSUE TITLE
Quick Query Regarding Cure-Please Not Casting Cure, But Will Cast Other Spells

### ISSUE THREAD

**Issue by honeycubbinz** [DanielHazzard/Cure-Please#50]
I ran into an issue where I can click auto-protect and it will cast that, but it will not cast cure automatically.

I tried a few different things like:

1) Made sure the port numbers are the same in the .lua file and in game but if they were different, I assume I wouldn't be able to even do auto-protect.

2) Both applications ran as admin (Ashita, Cureplease)

3) Application unpaused

4) User Account security settings as low as possible 

I only know a little about coding / networking so any ideas would be very helpful and thank you for your time.

Brandon

**Comment by DanielHazzard** [comment]
Either you've accidentally disabled the Cure spells by removing the tick from the checkbox, or the Cure amounts / threshold is too high/low.
