### ISSUE TITLE
Not Casting GEO-Malaise or tagging right

### ISSUE THREAD

**Issue by Mcluv** [DanielHazzard/Cure-Please#51]
If i have it set to cure party member to tag it will just keep casting cure over and over even with no bubble out. 1st priority should be GEO* spells over other geo stuff since its most potent. would be nice to tag with cure because can get aoe hate if tank hits them all first and then engages. i got it to work using stone 1 but should put bubble out first. It casts GEO-Malaise near end of fight after mob has tp'd a few times and chased healer down so now its out of place of other bubbles.

**Comment by jeffsanford** [comment]
I cant really tell whats going on on next mob its just spamming assist or trying to target the mob for a split second then removing target over and over and says a command error occurred in log and never gets GEO spell off. after 5 min of meleeing the apex crab if finally got bubble out.
My settings look right. any idea why its constantly assisting?
