### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by tipwell** [DanielHazzard/Cure-Please#52]
Getting a lot of those.. not sure what's causing it. Using CurePlease_v2.0.3.7_RC2.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CurePlease.Form1.<RunDebuffCheckerAsync>d__145.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Cure Please
    Assembly Version: 2.0.3.7
    Win32 Version: 2.0.3.7
    CodeBase: file:///C:/Users/xxx/Desktop/CurePlease_v2.0.3.7_RC2/Cure%20Please.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
EliteMMO.API
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Users/xxx/Desktop/CurePlease_v2.0.3.7_RC2/EliteMMO.API.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by DanielHazzard** [comment]
I'm just testing a fix, and should have it released within the next 24 hours if all goes well, Sorry about this.

**Comment by tipwell** [comment]
No problem Daniel, huge thanks for all your hard work!

**Comment by DanielHazzard** [comment]
So I've not had any replies from anyone on if it fixes the problem, I assume they've not yet had time. 

I'll add the BETA version to try here, you must use the ADDON for the Hook you use Windower/Ashita just copy the Folder CurePlease_Addon from the Hook version to your addons folder.

[CurePlease_BETA.zip](https://github.com/DanielHazzard/Cure-Please/files/3026711/CurePlease_BETA.zip)

**Comment by tipwell** [comment]
I will test it and let you know here. Thanks!

**Comment by tipwell** [comment]
So far, I was not able to reproduce the original issue. I've had one instance were both Cure Please and the monitored player instance just closed upon zoning, but I was unable to reproduce it. So  it may just have been a fluke.

On a site note, I feel this version is very inconsistent in removing party -na debuffs/erase. I've had better success with RC2 (same config file). I will test that portion further.

**Comment by DanielHazzard** [comment]
Debuffs.xml was never implemented as I found an alternate method to do so, you can just delete that.

**Comment by Velasquez-Marc** [comment]
I have been using the beta version for a bit of time now and I have not had issue with the error that started this thread. Which is very nice as the error was quite annoying thanks for all your work here.

**Comment by DanielHazzard** [comment]
Glad to hear, closing issue.
