### ISSUE TITLE
buff casting loop

### ISSUE THREAD

**Issue by Ba1dw1n** [DanielHazzard/Cure-Please#54]
First of all, thanks for you're great work. I have been using you're version of cureplease for sometime. 

The issue I am having is that when I use a few autospells for a PC the spell gets stuck in a loop. for example when I select haste II for a certain PC, it might just keep recasting that spell disregarding that It was just casted last on that PC and that the buff is still active, or that it has other buffs to cast on other pc's. As soon as its off cooldown it cast the spell immediately again on the same PC.  It seems to only happen when I have a few different buffs set up for different PC's.  The only way i can get it to stop is by manually unloading the cureplease_addon. As soon as i unload it it goes back to normal, casting the buffs appropriately as they wear off for each PC.

I will note I am using the same PC to run 6 different instances of FFXI as well as a few instances of cureplease, but I do have each addon/exec running on its own port and have checked using the checkport command. Also, I am using 3-5 instances of the bot Eazyfarm. this issue didnt seem to happen a month ago with the same versions that I am using which are all the latest.

What I cant tell you if the issue exist when only using one instance of FFXI, but i can say that it exist when using only one instance of cureplease for me.

Thanks in advanced and please keep up the excellent work!

**Comment by DanielHazzard** [comment]
All buffs, or only specific ones?

**Comment by Ba1dw1n** [comment]
Sorry for my late reply. Seems like it's all buffs that I select for an individual character, like selecting haste II for one and refresh 2 for another. It will get stuck on casting haste 2 over and over when it cools down but still healing regularly in between. Then if I deselect haste 2 for that character it will loop refresh 2 for the other. When I unload the addon it immediately corrects itself.
