### ISSUE TITLE
im on ashita and my party buffs are not showing 

### ISSUE THREAD

**Issue by Darkdante44** [DanielHazzard/Cure-Please#57]
Im on ashita and my party buffs dont show up so the cure - na spells for party members doesnt work, can you help me out. I read the other similar issues but none of them actually worked for me.

**Comment by DanielHazzard** [comment]
You could be using an older version, could you confirm whether the AddOn button in the attached version shows Red or Green when loaded and attached.

[CurePlease.zip](https://github.com/DanielHazzard/Cure-Please/files/3207068/CurePlease.zip)

**Comment by Darkdante44** [comment]
its red

**Comment by DanielHazzard** [comment]
Means something is interfering with the connection.

You'll need to check a few things.

1. Confirm CurePlease is allowed access through your firewall, as despite it only using the localhost it still requires access.

2. If it is allowed access through the Firewall confirm that the addon is loaded when the character is selected.

3. If it loads successfully confirm that the Addon and CurePlease share the same IP and port. This can be done by opening options and navigating to the options page, then with the addon loaded run the chat command : _/cpaddon check_ which should show a message similar to 

> [Cure Please Addon] IP Address: 127.0.0.1 / Port number: 19203

Compare that between the two.

Should you do this and they are all correct can you reply and I'll look into more in depth options.

**Comment by DanielHazzard** [comment]
Assumed fixed.

**Comment by Darkdante44** [comment]
its works when it wants to sometimes it works and sometimes it doesn't idk what im doing wrong.
