### ISSUE TITLE
v2.0.3.9 - Afflatus : 

### ISSUE THREAD

**Issue by heghmoh** [DanielHazzard/Cure-Please#58]
In this version update the command for Afflatus Misery and Afflatus Solace has a ":", causing a command error to spam in client and forcing a attempted buff loop on the bot. 

Command should be /ja "Afflatus Solace" <me>, not /ja "Afflatus: Solace" <me>

**Comment by DanielHazzard** [comment]
Pushed a fix to releases.

**Comment by DanielHazzard** [comment]
Issue was fixed.
