### ISSUE TITLE
Accession

### ISSUE THREAD

**Issue by BombSDiggity** [DanielHazzard/Cure-Please#59]
keeps attempting to utilize accession but there is a minor typo preventing it from functioning. 
it types /ja "Acccession" <me> instead of /ja "Accession" <me>

**Comment by DanielHazzard** [comment]
Pushed a fix.

**Comment by BombSDiggity** [comment]
Dude, you're the man for real. Does it auto update or do I redownload it?Sent via the Samsung Galaxy S8+, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Daniel Hazzard <notifications@github.com> Date: 5/25/19  4:00 PM  (GMT-08:00) To: DanielHazzard/Cure-Please <Cure-Please@noreply.github.com> Cc: BombSDiggity <elliston.ryan@gmail.com>, Author <author@noreply.github.com> Subject: Re: [DanielHazzard/Cure-Please] Accession (#59) Pushed a fix.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DanielHazzard/Cure-Please/issues/59?email_source=notifications\u0026email_token=AMFLGPSATG4PAET4X6AZCJTPXHAHNA5CNFSM4HPVJ2C2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWH2VBY#issuecomment-495954567",
"url": "https://github.com/DanielHazzard/Cure-Please/issues/59?email_source=notifications\u0026email_token=AMFLGPSATG4PAET4X6AZCJTPXHAHNA5CNFSM4HPVJ2C2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWH2VBY#issuecomment-495954567",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by BombSDiggity** [comment]
Does it auto update or do i need to redownload it? for the record you're the freakin man
