### ISSUE TITLE
Debuff removal is not working. [V2.0.3.7]

### ISSUE THREAD

**Issue by Aeyliea** [DanielHazzard/Cure-Please#61]
CurePlease will not pick up debuffs currently on the party for any reason.  I have verified that the port in game via cpaddon check and the one in program options are the same.  I turned my all of my firewalls and it still will not read party buffs.  It also seems to have some trouble curing in alliance settings, but it will not remove debuffs under any circumstance whatsoever.

Been battling this for  month now.  Any ideas?

**Comment by DanielHazzard** [comment]
Does the ADDON button light green?

**Comment by Aeyliea** [comment]
Red light, no buffs show.  Went through and checked ports, tried allowing it to work through firewall and ultimately disabled firewall and it made no difference.

**Comment by DanielHazzard** [comment]
Somewhere the data is not being sent, I'd double check that you are using the newer addon with it.

**Comment by rivan48312** [comment]
Where is the newer addon file located?
