### ISSUE TITLE
REQUEST: Enfeebling magic Tab

### ISSUE THREAD

**Issue by R3P0FFXI** [DanielHazzard/Cure-Please#62]
@DanielHazzard  please add tabs for Enfeebling Magic

Please add a tab for Enfeebling magic similar to enhancing magic setup, have the program assist and then use enfeebling magic on engaged mobs Paralyze Bio Dia Slow etc

**Comment by DanielHazzard** [comment]
I am no longer adding anything new to CurePlease.
