### ISSUE TITLE
Auto refresh 3

### ISSUE THREAD

**Issue by rain305mike** [DanielHazzard/Cure-Please#63]
the auto refresh isnt workign and I set it to refresh 3  if I pick multi people in my group which I pick 3 ppl in my party for refresh only 1 gets it and doesnt auto refresh 3 other 2 any reason?  and sometime the auto haste2 if you pick 3 people sometimes only does 1 - 2 people

**Comment by rain305mike** [comment]
DanielHazzard anyway I can add you on discord and ask you few questions please

**Comment by DanielHazzard** [comment]
I think at this point the whole "Auto" section needs to be rewritten, the problem is finding the time to do so.

And yes, Daniel_Hazzard#5001
