### ISSUE TITLE
Could you add edenxi.exe as well? They implemented a new boot-loader that you cannot rename. Thanks

### ISSUE THREAD

**Issue by tipwell** [DanielHazzard/Cure-Please#65]
FFXI cannot be found; Eden private server implemented a new boot-loader (edenxi.exe) that cannot rename. Could you add it to the search? See https://github.com/DanielHazzard/Cure-Please/issues/14#issuecomment-519064181_

Thanks,

**Comment by DanielHazzard** [comment]
Done,  added in 2.0.4.0 release.
