### ISSUE TITLE
problem with addon 

### ISSUE THREAD

**Issue by Darkdante44** [DanielHazzard/Cure-Please#68]
![Kimbo_2019 08 20_145252](https://user-images.githubusercontent.com/18201535/63375695-42ff2080-c35a-11e9-87ab-c4e116107ab7.png)

I use cureplease all the time , but when i updated to the 2.0.4.0 this is happening when i select pl and monitored

**Comment by DanielHazzard** [comment]
Hmm. I would assume ashita removed the Packets require, I will look into this tomorrow.

Sorry about that.

**Comment by DanielHazzard** [comment]
Update: Can you double check you're using the newest Addon as it doesn't use packets.lua.

**Comment by Darkdante44** [comment]
Hmm maybe I didnt i did it over again and it worked this time, my apologies.
