### ISSUE TITLE
Suggestion: More Debuffs

### ISSUE THREAD

**Issue by bjggi** [DanielHazzard/Cure-Please#70]
Would it be possible to add more Spell options for Debuffs. Like the "Auto Casting Spells" but with more options. Specially for RDM great, so it could add more stuff like Addle II, Para, Dia 3, etc. Atm im still using healbot for debuffs.

Thank you for your Work, really appreciate what u do, we use CP alot ;)
Best regards

**Comment by DanielHazzard** [comment]
I think it'd be better to write this in a completely separate bot as it'd require many checks to be added including chat log reading, as such if I were to add it it'd be as a separate bot.
