### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by Lockinvarr** [DanielHazzard/Cure-Please#71]

**Comment by DanielHazzard** [comment]
Double check EliteAPI.dll is not blocked by right clicking > Properties the DLL and enabling it if locked.

If that is not the case double check EliteAPI.dll and EliteMMO.API.dll are in the same directory as Cure Please.exe

**Comment by Lockinvarr** [comment]
EliteAPI.dll is unblocked and both files are in the same folder, but getting the same error message. Thanks for replying. Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Daniel Hazzard <notifications@github.com> Date: 9/16/19  4:06 AM  (GMT-05:00) To: DanielHazzard/Cure-Please <Cure-Please@noreply.github.com> Cc: Lockinvarr <friddled81@gmail.com>, Author <author@noreply.github.com> Subject: Re: [DanielHazzard/Cure-Please] Getting an error (#71) Double check EliteAPI.dll is not blocked by right clicking > Properties the DLL and enabling it if locked.
If that is not the case double check EliteAPI.dll and EliteMMO.API.dll are in the same directory as Cure Please.exe

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DanielHazzard/Cure-Please/issues/71?email_source=notifications\u0026email_token=ANFQ2FU3CX4ZLC4INDVJ7GLQJ45ABA5CNFSM4IWG4SEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6YMNUQ#issuecomment-531678930",
"url": "https://github.com/DanielHazzard/Cure-Please/issues/71?email_source=notifications\u0026email_token=ANFQ2FU3CX4ZLC4INDVJ7GLQJ45ABA5CNFSM4IWG4SEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6YMNUQ#issuecomment-531678930",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DanielHazzard** [comment]
Do other EliteAPI apps work for you?

**Comment by Lockinvarr** [comment]
No they don't Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Daniel Hazzard <notifications@github.com> Date: 9/23/19  3:12 AM  (GMT-05:00) To: DanielHazzard/Cure-Please <Cure-Please@noreply.github.com> Cc: Lockinvarr <friddled81@gmail.com>, Author <author@noreply.github.com> Subject: Re: [DanielHazzard/Cure-Please] Getting an error (#71) Do other EliteAPI apps work for you?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DanielHazzard/Cure-Please/issues/71?email_source=notifications\u0026email_token=ANFQ2FVKGYYSFTFGTBL52ZDQLBT7JA5CNFSM4IWG4SEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7J7ERA#issuecomment-533983812",
"url": "https://github.com/DanielHazzard/Cure-Please/issues/71?email_source=notifications\u0026email_token=ANFQ2FVKGYYSFTFGTBL52ZDQLBT7JA5CNFSM4IWG4SEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7J7ERA#issuecomment-533983812",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DanielHazzard** [comment]
I'd verify you have the required Microsoft installs.

https://download.microsoft.com/download/5/B/C/5BC5DBB3-652D-4DCE-B14A-475AB85EEF6E/vcredist_x86.exe
https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU3/vcredist_x86.exehttps://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe
https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe

**Comment by Lockinvarr** [comment]
Thanks man that fixed it!Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Daniel Hazzard <notifications@github.com> Date: 9/29/19  8:09 AM  (GMT-05:00) To: DanielHazzard/Cure-Please <Cure-Please@noreply.github.com> Cc: Lockinvarr <friddled81@gmail.com>, Author <author@noreply.github.com> Subject: Re: [DanielHazzard/Cure-Please] Getting an error (#71) I'd verify you have the required Microsoft installs.
https://download.microsoft.com/download/5/B/C/5BC5DBB3-652D-4DCE-B14A-475AB85EEF6E/vcredist_x86.exe
https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU3/vcredist_x86.exehttps://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe
https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DanielHazzard/Cure-Please/issues/71?email_source=notifications\u0026email_token=ANFQ2FUM4YITXI5KCSNNN23QMCLIVA5CNFSM4IWG4SEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD73S6KI#issuecomment-536293161",
"url": "https://github.com/DanielHazzard/Cure-Please/issues/71?email_source=notifications\u0026email_token=ANFQ2FUM4YITXI5KCSNNN23QMCLIVA5CNFSM4IWG4SEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD73S6KI#issuecomment-536293161",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
