### ISSUE TITLE
Multibox/Multi Cureplease opend at once...

### ISSUE THREAD

**Issue by Comgamer7** [DanielHazzard/Cure-Please#72]
Hello, i run 3 chars almost always. I use cureplease on all 3 most of the time for different things... Is there a way to run the addon on all 3 or can it only be active on 1 of the cureplease applications? I mainly leave the active one as my WHM so debuffs go off as fast as possible, the other 2 dont always buff/debuff when it should.

**Comment by DanielHazzard** [comment]
Yes, make sure each has a different Port Number.

**Comment by Comgamer7** [comment]
Oh sweet thanks!

**Comment by Comgamer7** [comment]
When i changed the port number, it just changes back.

**Comment by DanielHazzard** [comment]
If you have AutoLoad settings, then you need to change the port number after selecting the PL.

So you'd Select PL which would load the XML, the change the Port Number, I then suggest you save the XML again. Do the same for all three, then never worry about it again.

**Comment by Comgamer7** [comment]
Ok ill try it that way, ty

**Comment by Comgamer7** [comment]
Worked, TY!!!!!!!!!!!!

**Comment by DanielHazzard** [comment]
Glad to hear, closing issue then.
