### ISSUE TITLE
Auto Casting Spells: Party Based

### ISSUE THREAD

**Issue by bjggi** [DanielHazzard/Cure-Please#73]
I have a Question. I would like to use the **Auto Casting Spell Option: Party Based** for my Geo. But when i enter "Spell Type": **Party Based** | "Spell Name": **Cure** the Geo will Cast Cure on the engaged Mob, instead of the Player. I think there is something wrong, or maybe i am missing something.

In regards of this Option, would it be possible to make the Party Based Spell available for the Alliance (maybe this is already the case not sure), so a Geo could cure a Tank or Puller in another Party, to get Hate on all Mobs. Would be great!

Thank you

**Comment by DanielHazzard** [comment]
This is with you setting the Player name in Target?

Setting that will simply set the spell to be cast on that target, so should work in the scenario you want.

**Comment by bjggi** [comment]
Yeah, just double checked again. When i enter the Monitored Player's Name or someone else in the Target field it still cures the Mob.

Using V 2.0.4.0

**Comment by DanielHazzard** [comment]
Okay, I'll check it out as it could be I messed with it by accident when rewriting GEO.

**Comment by DanielHazzard** [comment]
[Cure Please.zip](https://github.com/DanielHazzard/Cure-Please/files/3615220/Cure.Please.zip)

Hello, 

could you check this version.

**Comment by bjggi** [comment]
Works! On Alliance Members too, thank you!

**Comment by DanielHazzard** [comment]
np, glad to hear.
