### ISSUE TITLE
Program Options / Other Options #2

### ISSUE THREAD

**Issue by Shiva219** [DanielHazzard/Cure-Please#74]
Hello, I just have two quick questions. Does the “Reduce recast timer by 50%” work? I’m asking because every version I’ve had of cure please it’s grayed out and can’t be enabled. Second question, is the “Other Options #2” tab something for future builds or is that supposed to have more options in it. Mine is blank so wanted to make sure mine wasn’t broke.

**Comment by DanielHazzard** [comment]
No, that was disabled after I got the packet reading working correctly, I keep forgetting to remove it.

Options #2, was intended for something, but I stopped working on it, that also needs to be removed.
