### ISSUE TITLE
Question about Menu/Auto Buttons

### ISSUE THREAD

**Issue by zombie343** [DanielHazzard/Cure-Please#75]
Are the contents of the Menu/Auto Buttons configurable?  I currently have Auto-Storms listed, but they only cast Storm 1 spells. I'd like to make Storm 2 spells available to be cast on those players via Menu/Auto buttons. Is this possible?

Thanks!

**Comment by Wotasu** [comment]
You have to set Stormspell Tier II under Option > Enhancing > Basic Enhancing, Here you can set if it's refresh 1>3, regen 1>5, Pro/shell 1>5  & which Storm tier 1>2.

**Comment by zombie343** [comment]
Thank you so much! That did the trick! Closing this issue.
