### ISSUE TITLE
Accession+Perpetunace+Regen V dont work

### ISSUE THREAD

**Issue by Wotasu** [DanielHazzard/Cure-Please#76]
Any Accession+Perp+Regen I-IV works ok, but not Regen V. 
It will Accession but wont use Perpetuance, if I manually use Perpetuance it will RegenV right after if Accession is up.
If I set Accession + Regen V it works also.

**Comment by DanielHazzard** [comment]
Ok, I'll look into it.

**Comment by Wotasu** [comment]
Did some further testing, I was wrong with Acc+Perp+Regen 1-4 working. Only under Accession.
Acc + Perp + Phalanx/Refresh(if sublimation on will keep trying Refresh it seems)/Aquaveil/Storm/Stoneskin works. Blink isnt triggering at all for Acc+Perp. Only really bothered about the Regen part. 
Thank you for working on it!  :)

**Comment by Lordgenbu** [comment]
I second this motion, I love this so much but Regen V doesn't work. It makes it to where I can't AFK with SCH at all.

**Comment by DanielHazzard** [comment]
Pushing a fix in 5 minutes.

**Comment by Wotasu** [comment]
Working wonders! Thank you for your work :)
