### ISSUE TITLE
How to enable 2 instances at the same time with addon?

### ISSUE THREAD

**Issue by awildpotato1** [DanielHazzard/Cure-Please#77]
Hi, thanks for the great work.

Newer version doesnt seem to load the addon when 2 instances are run, for say WHM + GEO.
I tried changing the default port of the second window but didn't get anywhere. 
Anyone know how to fix this? 

The first instance loads and changes the Addon button to green.

EDIT:

Seems to be working but the actual UI AddOn stays red, but the addon does appear to load.

**Comment by DanielHazzard** [comment]
You need to make sure each instance has a separate port number before the AddOn is loaded.

Otherwise you need to update the addon with the command 
Windower
//cpaddon settings IPADDRESS PORTNUMBER

Ashita
/cpaddon settings IPADDRESS PORTNUMBER
