### ISSUE TITLE
Stormspell Tier II + Autocast/PL buffing not working

### ISSUE THREAD

**Issue by DracoRyx** [DanielHazzard/Cure-Please#78]
So with the client enabled on my SCH99/RDM49, setting the options to "Stormspell Tier II" in the auto spell listing and Rainstorm II in the PL buff section seems to just disable casting entirely for storm spells from the bot. I've got 120 JP and definitely have tier 2 storm spells unlocked, but the bot seems to not realize this, or want to cast them.

This is my settings that aren't working, it was fixed by simply changing Rainstorm II to Rainstorm, and Stormspell Tier II to Tier I, with the same timer.

![image](https://user-images.githubusercontent.com/5627624/67619011-3e684580-f7ab-11e9-94ce-2b40fa0ab255.png)

**Comment by DanielHazzard** [comment]
I'll check it out.

**Comment by zombie343** [comment]
bumpity bump bump :)
