### ISSUE TITLE
Unsure if its an issue, or just not enabled yet: Reduce Cure Casting Timer

### ISSUE THREAD

**Issue by KnifeKat** [DanielHazzard/Cure-Please#80]
Just wondering if its just in there because its being implemented, or if its greyed out for a reason I am unaware of/how to enable it?

I appreciate it, by the way.

I've also noticed that I don't seem to be using Accession with Regen IV at all ever since roughly a week or two ago. 

Mule will use Accession at the start of a buff cycle but never reserve it for Regen IV(What I would preferably want.)

She has Yagrush, so I only really need Accession for Regen IV now. Unsure how to force this, without it just using it when its available. 

Thank you for all your hard work and I love this. Its made my toon a glorified Trust. xD

**Comment by DanielHazzard** [comment]
Was disabled when I added packet tracking as that works alot better.

I'll l.ook into further specification of accession.
