### ISSUE TITLE
SCH Storm Tier 2 don't work for more than one Auto-Storm click.

### ISSUE THREAD

**Issue by zombie343** [DanielHazzard/Cure-Please#83]
Observation: 
No matter how many different characters have different Auto-(Element)Storm2 clicked, only the most recent click takes effect, but for all characters with which Auto-{element}Storm was selected.

Steps to reproduce:

0.) Make a party of 6.
1.) Scholar is both Selected PL and Monitored Player
2.) Set StormType under Enhancing to Storm-Type II, 3.0 minutes duration.
3.) Select Auto-HailStorm on a person1 other than the SCH
4.) Select Auto-AuroraStorm on a person2 other than the SCH.
5.) Start CurePlease.

Only the most recent click (AuroraStorm) takes effect and both person1 and person2 and both players will receive Aurorastorm 2. (Person1 doesn't recieve Hailstorm 2 as was originally clicked). When selecting player1's Auto-Button it no longer says HailStorm as was clicked, it was replaced by AuroraStorm (the most-recent click).

Please help.

**Comment by DanielHazzard** [comment]
Okay, I'll look into it.

**Comment by zombie343** [comment]
Really appreciate your help in getting Storm 2's to work, Daniel. My LS will get a kick out of it during Dynamis runs where we bring Rangers for Trueflight spam (and need Aurorastorm II). Have a happy/healthy holiday too.

**Comment by wbnightwolf** [comment]
I can second this; and the recreation is spot on.  TY in advance for fixing :P

**Comment by DanielHazzard** [comment]
Hello, 

Are you able to confirm if this fix solves the problem for you?

[StormFix.zip](https://github.com/DanielHazzard/Cure-Please/files/4007812/StormFix.zip)

**Comment by zombie343** [comment]
Thank you so much for this patch. Here are my tests/observations.

1.) Started up Cure Please Storm Fix in a party of 5
2.) SCH is PL, Player1 is Monitored Player.
3.) SCH is configured to cast Aurorastorm 2 (Storm II spells clicked, every 3 minutes).
4.) In the main UI, I click Auto on Player1 and select Firestorm II
5.) In the main UI, I click Auto on Player2 and select Hailstorm II
6.) In the main UI, I click Auto on Player3 and select Thunderstorm II
7.) I press Start on Cure Please.
8.) Everything appears to work as normal. The order Storm 2 spells are cast on Player 1, 2 and 3 doesn't appear to follow any particular order. (This is fine, as I assume you're using an un-ordered map of some kind).
9.) Once Player1, 2 and 3 have their storm 2 spells cast on them, Cure Please will repeated cast the Storm II on the Monitored player repeatedly. It does this indefinitely, and immediately, as if the Buff ID for Storm II may no be correctly registering as Player1 having the fire storm 2 effect.

In this loop, the CurePlease text at the bottom says the following message over and over. I've removed my PL's name for posterity. 
See: [Imgur](https://imgur.com/wV32xyJ)

Also, it would see them that unchecking the box next to Player1 (Monitored Player) or unchecking Auto-FireStorm2 in this case, doesn't stop the loop, because Auto-Firestorm2 stays checked. :/

This seems like a close attempt. Thank you for your continued help. Your hardwork is appreciated!

**Comment by DanielHazzard** [comment]
Oh, that message was a debug message, should have removed it, I'll look into the monitored, I probably messed up and done a PL check over Monitored.

**Comment by DanielHazzard** [comment]
Hello,

I've rewritten the AUTO section, is it possible you could try this version.

[StormSpellFixMK2.zip](https://github.com/DanielHazzard/Cure-Please/files/4008391/StormSpellFixMK2.zip)

**Comment by zombie343** [comment]
Thank you again Daniel. Everything from my previous comment appears to be in working order. However, there is still a problem with the AUTO section. Once I've selected a Player for say FireStorm II, I can't seem to select it, such that FireStorm under AUTO, will become unchecked. (I can check another element, like Sandstorm, and that character will get Sandstorm II). 

So, it just appears that disabling storms for a specific character under the AUTO section doesn't seem to be working. (If there is another way to disable auto-storms, please let me know, as Auto-Regen under the AUTO menu does enable/disable accordingly, when clicked).

Thanks again! Your hardwork is greatly appreciated!

**Comment by DanielHazzard** [comment]
Ok, I shall fix that probably end of tomorrow.

**Comment by DanielHazzard** [comment]
Okay, I believe I've ironed out that bug as well.

[StormSpellFixMK3.zip](https://github.com/DanielHazzard/Cure-Please/files/4008910/StormSpellFixMK3.zip)

**Comment by zombie343** [comment]
Tested everything prior and the enable/disable of storms via AUTO menu. Everything works perfectly now. I'll wait patiently for your next release.
