### ISSUE TITLE
Multiboxing Second Client unable to see own buffs

### ISSUE THREAD

**Issue by Mcdougall1** [DanielHazzard/Cure-Please#85]
Hey Daniel_H..

With one client of CurePlease open and running everything works fine. 

When i open the second client and change the port addon enables. It sees buffs of all other characters but itself. Because it doesn't see its own buffs it spams spells over and over. I changed my port to 19800. It goes green on addon. Just doesn't see its own buffs... just everyone elses. Thank you dude.

**Comment by DanielHazzard** [comment]
The addon is not able to see it's own buffs in the PT Buffs tab as the packet only shows the 5 remaining party members bar trusts.
