### ISSUE TITLE
Request for PLD to be added to Job Abilities list.

### ISSUE THREAD

**Issue by anthem127** [DanielHazzard/Cure-Please#86]
With the new Job ability Majesty PLD is very good main heal now.  Would like to see something where it uses Majesty.  Would be extra cool if you could set a timer between JA and then set an order of use.  Something like.
1 Sentinel 
2 Rampart 
3 Warcry
etc

And have a timer where you can set it in 1-3 minute increments. This would allow PLD to main heal in DDyna and keep hate.  Random Idea, would be happy if just Majesty was added.

**Comment by Swystix** [comment]
Hello, I would like to ask for PLD to be added as well.

The ability to auto cast reprisal when the timer is ready would be useful, enlight as well with what was mentioned above.

Thank you!

**Comment by Vamperica** [comment]
Also needs to add enhancing spells:

Enlight I & II
Reprisal
Crusade
