### ISSUE TITLE
Afflatus Solace (WHM)

### ISSUE THREAD

**Issue by bjggi** [DanielHazzard/Cure-Please#88]
Somehow the **Afflatus Solace** JA is getting used last as a WHM/SCH. I think u fixed this on Issue 66:
https://github.com/DanielHazzard/Cure-Please/issues/66 but somehow it still is used last on 2.0.4.2

Maybe this got overwritten again?

Would be great if u could check it out.

Thanks

**Comment by DanielHazzard** [comment]
It did indeed get removed by accident, will be fixed in the next release, sorry about that.
