### ISSUE TITLE
ffxi not found

### ISSUE THREAD

**Issue by sambushme** [DanielHazzard/Cure-Please#89]
I saw you have 2 other issues that have been closed with a similar issue.
I was hoping you could add the exe below. I am completely assuming this is the issue with trying to run the Cure-Please with Ashita.
I did add the CurePlease_Addon folder to the Ashita > Scripts > Addons directory but still the same issue. 
If you believe it could be something else other than the exe please let me know. 
Thank you

File: .\\ffxi-bootmod\\boot.exe

** I renamed boot.exe to pol.exe and now I am able to select the PL and the player to monitor. However, the addon buton is red and I am getting a bunch of red errors. 
I triple checked and I copied over the Ashita Add-on folder to the Addons directory. But still nothing.

**Comment by DanielHazzard** [comment]
As with all boot loaders, they must be named pol.exe to work with CurePlease.

So your Addon folder should be as follows to work correctly: 

Ashita 
> Addons
>> CurePlease_Addon
>>> CurePlease_Addon.lua
