### ISSUE TITLE
ST20 (Incorrect Spells mapped for removal)

### ISSUE THREAD

**Issue by beerman212** [DanielHazzard/Cure-Please#91]
Status Effect 20 (StatusEffect.Curse2) is unremovable via the spell Cursna.

It has to be removed via Esuna (on PL), or Sacrifice (on Party Member).  It cannot be removed from Alliance.

Line 4135:
`
else if ((plEffect == StatusEffect.Curse2) && (Form2.config.plCurse2) && (CheckSpellRecast("Esuna") == 0) && (HasSpell("Esuna")) && JobChecker("Esuna") == true)
{
  CastSpell(_ELITEAPIPL.Player.Name, "Esuna");
}
`

Line 4331:
`
else if ((monitoredEffect == StatusEffect.Curse2) && (Form2.config.monitoredCurse2) && (CheckSpellRecast("Sacrifice") == 0) && (HasSpell("Sacrifice")) && JobChecker("Sacrifice") == true)
{
  // Probably need a check for in party with whm here...
  CastSpell(_ELITEAPIMonitored.Player.Name, "Sacrifice");
}
`

I don't see any logic for it for other party members.

**Comment by DanielHazzard** [comment]
As with your other topic, this will be pushed to the next release, Thank you again.
