### ISSUE TITLE
Disabling PL Attack Down removal will disable Erase casting on PL.

### ISSUE THREAD

**Issue by beerman212** [DanielHazzard/Cure-Please#92]
When checking Debuffs on PL, if the check box for Attack Down removal on PL is unchecked, all erasable debuffs will return false when checking the debuff because there is a check to that box on all of them.

`
else if ((plEffect == StatusEffect.Burn) && (Form2.config.plBurn) && (Form2.config.plAttackDown) && (CheckSpellRecast("Erase") == 0) && (HasSpell("Erase")) && JobChecker("Erase") == true)
                    {
                        CastSpell(_ELITEAPIPL.Player.Name, "Erase");
                    }
                    else if ((plEffect == StatusEffect.Frost) && (Form2.config.plFrost) && (Form2.config.plAttackDown) && (CheckSpellRecast("Erase") == 0) && (HasSpell("Erase")) && JobChecker("Erase") == true)
                    {
                        CastSpell(_ELITEAPIPL.Player.Name, "Erase");
                    }
                    else if ((plEffect == StatusEffect.Choke) && (Form2.config.plChoke) && (Form2.config.plAttackDown) && (CheckSpellRecast("Erase") == 0) && (HasSpell("Erase")) && JobChecker("Erase") == true)
                    {
                        CastSpell(_ELITEAPIPL.Player.Name, "Erase");
                    }
`

A few examples.  Form2.config.plAttackDown should be removed as a check.

**Comment by DanielHazzard** [comment]
Thank you, I'm not sure how I missed that.

Although, looking at that section it's possible I never noticed as I personally did not write that section.

This has been corrected now and will be pushed to the next release (next couple of days)
