### ISSUE TITLE
Auto Casting Spells - Enemy Based

### ISSUE THREAD

**Issue by CoCoHimself** [DanielHazzard/Cure-Please#96]
Having an issue with my PL not casting on the target.

Update:. Pretty sure it was me/user error.  I was loading the save config

**Comment by DanielHazzard** [comment]
So this now works for you?

**Comment by CoCoHimself** [comment]
Yes, it is working.  To confirm when make changes to the options and save, is it best practice to reload the addon?

**Comment by ShoppyCodes** [comment]
Having this problem currently. It seems to do it once randomly when you press start but then never again. Trying to get hate on enemy for GEO.

**Comment by DanielHazzard** [comment]
No, the addon should work fine without reloading so long as you don't change IP or PORT after loading PL and Monitored.
