### ISSUE TITLE
Request: Pause/start from game?

### ISSUE THREAD

**Issue by JackSparrow6969** [DanielHazzard/Cure-Please#97]
Hello,

Thank you so much for this project!  It is absolutely awesome and very appreciated.

Maybe I’m just stupid, but I haven’t seen it anywhere;

Is it possible to start/pause cure please from in-game? And if not, could that be possible?  I’m assuming since there’s an addon maybe it’s possible.

Thank you again!

**Comment by DanielHazzard** [comment]
Yes, there is currently two ways

//cpaddon cmd (stop/pause | start/unpause | toggle)

or

//cureplease COMMAND

start or unpause = unpauses the bot
stop or pause = pauses the bot

You can further specify this by added the characters name you want to modify after the action
Example: cureplease pause JohnDoe

**Comment by JackSparrow6969** [comment]
Oh awesome, thank you again!
